### DISCUSSION TITLE
Should we continue to use Sidekiq as our preferred queuing backend?

### DISCUSSION THREAD

**Discussion by stevepolitodesign** [thoughtbot/suspenders#1298] [General]
The [upcoming release of Rails 8](https://github.com/rails/rails/issues/50442) is slated to use [Solid Queue](https://github.com/rails/solid_queue) as the default queuing backend.

We currently [default to Sidekiq](https://github.com/thoughtbot/suspenders/blob/main/lib/generators/suspenders/jobs_generator.rb).

Should we continue to use Sidekiq as our preferred queuing backend, or, should we use the new Rails default?

**Comment by stevepolitodesign** [comment]
If we're not ready to use Solid Queue in favor of Sidekiq, we should skip it with `--skip-solid` when running [rails new](https://edgeguides.rubyonrails.org/command_line.html#rails-new)

**Comment by stevepolitodesign** [comment]
Another thing to consider is hosting. If we don't call `--skip-solid`, then we end up with 4 databases:

```
production:
  primary: &primary_production
    <<: *default
    database: rails_8_production
    username: rails_8
    password: <%= ENV["RAILS_8_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_8_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_8_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_8_production_cable
    migrations_paths: db/cable_migrate
```
