### ISSUE TITLE
How do we want to handle code auditing now that Rails ships with a solution?

### ISSUE THREAD

**Issue by stevepolitodesign** [thoughtbot/suspenders#1215]
[Rails 7.2](https://edgeguides.rubyonrails.org/7_2_release_notes.html) now ships with [brakeman](https://github.com/rails/rails/pull/50507).

However, with the introduction of #1138, we risk having two auditing mechanisms.

**Comment by stevepolitodesign** [comment]
One solution could be to simply skip this option.

https://github.com/rails/rails/blob/ff0ef93e28d4919ffd8bf130132b7b7e3435c67a/railties/lib/rails/generators/app_base.rb#L105

**Comment by stevepolitodesign** [comment]
Alternatively, we keep it, and just make sure CI runs the command. Below is from a fresh Rails 8 install.

```yaml
jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

```
