### ISSUE TITLE
Circle auto-deploys not working

### ISSUE THREAD

**Issue by iwz** [thoughtbot/suspenders#594]
It seems that we may be missing a piece or two to get new apps up and running with auto-deploys from circle.

We may need to add the git remote called `staging`, pointed to the correct heroku app:

```yaml
test:
  pre:
    - cp .sample.env .env
deployment:
  staging:
    branch: master
    commands:
      - git remote add staging git@heroku.com:APP_NAME.git
      - ./bin/deploy staging
```

We also need to configure Circle's settings with the Heroku API and SSH key. This is a manual step, AFAICT, and it's not documented in this repo, I don't think.
