### ISSUE TITLE
Deploy on CircleCI

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/suspenders#687]
We add lines to [`circle.yml`] (https://github.com/thoughtbot/suspenders/blob/77d3310dd1d531a04aae4e4621fc55ff8168d7e5/lib/suspenders/app_builder.rb#L421-L422) for deploying the code automatically when the build is green. But CircleCI doesn't have the right Git repositories configured to be able to deploy to Heroku as staging. Should we remove that configuration? Or is there a well-known step that needs to be performed?

**Comment by tute** [comment]
In my last project I added the remote myself before deploy:

```yaml
deployment:
  staging:
    branch: master
    commands:
      - git remote add staging git@heroku.com:appname-staging.git
      - bin/deploy staging
```

We can easily add that to suspenders.

We can deploy from GitHub too. Do we have a preferred method for any reason?
