### ISSUE TITLE
Point default Hound configurations to our Guides repo

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/suspenders#695]
Some discussion over on https://github.com/thoughtbot/guides/pull/379 happened around pointing the [default Hound configuration](https://github.com/thoughtbot/suspenders/blob/master/templates/hound.yml) here in Suspenders to look at standardized linter configs in our Guides repo.

- This means we could establish standard configurations in our Guides repo, that match our style, right next to all of our other documentation regarding code style
- It also means new Suspenders projects will kick-off with Hound configured directly to our thoughtbot style, whereas right now it is whatever Hound is defaulted to (which we are split on whether that should be _our_ guidelines, or the default of each linter we use, or something else)

**Comment by tysongach** [comment]
So I believe it would be something like this: (as an example)

```yaml
# hound.yml

scss:
  config_file: https://raw.githubusercontent.com/thoughtbot/guides/tg-scss-lint/style/sass/scss-lint-config.yml
  enabled: true
```
